export const actionTypes = {
  //Chart Action Types
  ADD_CHART_CARD: "ADD_CHART_CARD",
  UPDATE_CHART_CARD: "UPDATE_CHART_CARD",
  REMOVE_CHART_CARD: "REMOVE_CHART_CARD",

  ADD_CHILD: "ADD_CHILD",
  REMOVE_CHILD: "REMOVE_CHILD",
  ADD_SIBBLING: "ADD_SIBBLING",
  UPDATE_NODE: "UPDATE_NODE",

  GET_CHART: "GET_CHART",
  UPDATE: "UPDATE",
};
